name = "DiefAlpha MCPack"
author = "DieAlpha"
version = "1.20.1-1.0.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2754d39f41cb36ad46a3f56a9a03e871087d0bcc939420e299c0bf21ad206638"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
