name = "DiefAlpha MCPack"
author = "DieAlpha"
version = "1.20.1-1.0.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba4bde08149e6ed6147310eb5818ffe92db0491984d4392f845beceb8e883ac7"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
