name = "DiefAlpha MCPack"
author = "DieAlpha"
version = "1.20.1-1.0.0-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2753a0c8920262cca7d68fd0b95c588cfd3414ff67281ec7a82cc7bea4e874d3"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
